# Generated by Django 2.1.11 on 2019-12-23 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmc', models.CharField(max_length=32)),
                ('full_paper', models.TextField()),
                ('pmid_cited', models.TextField()),
                ('doi_cited', models.TextField()),
                ('references', models.TextField()),
                ('images', models.TextField()),
                ('tables', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('English', 'English'), ('Chinese', 'Chinese')], default='English', max_length=16)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('tags', models.CharField(max_length=255)),
                ('liked_num', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Checked', 'Checked'), ('Submitted', 'Submitted')], default='Submitted', max_length=16)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField()),
                ('authors', models.TextField()),
                ('doi', models.CharField(max_length=255)),
                ('pmid', models.IntegerField(unique=True)),
                ('title', models.TextField()),
                ('journal', models.CharField(max_length=128)),
                ('mesh_terms', models.TextField()),
                ('publication_types', models.CharField(max_length=32)),
                ('chemical_list', models.CharField(max_length=128)),
                ('reference', models.TextField()),
                ('delete', models.BooleanField(default=False)),
                ('affiliations', models.TextField()),
                ('pmc', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('medline_ta', models.CharField(max_length=32)),
                ('nlm_unique_id', models.CharField(max_length=16)),
                ('issn_linking', models.CharField(max_length=32)),
                ('other_id', models.CharField(max_length=32)),
                ('keywords', models.CharField(max_length=255)),
                ('pubdate', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='knowledge',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Paper'),
        ),
        migrations.AddField(
            model_name='fullpaper',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Paper'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledge',
            unique_together={('author', 'paper', 'language')},
        ),
    ]
