# Generated by Django 2.1.11 on 2019-12-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_paper_knowledge_fullpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publication_types',
            field=models.TextField(),
        ),
    ]
