# Generated by Django 2.1.11 on 2019-12-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_paper_fileds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='reference',
            new_name='references',
        ),
        migrations.AlterField(
            model_name='paper',
            name='chemical_list',
            field=models.TextField(),
        ),
    ]
