# Generated by Django 2.1.11 on 2019-12-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_make_pmid_as_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='affiliations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='chemical_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='issn_linking',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='medline_ta',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='mesh_terms',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='nlm_unique_id',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='other_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pmc',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pubdate',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publication_types',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='references',
            field=models.TextField(null=True),
        ),
    ]
