# Generated by Django 2.1.11 on 2020-01-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_set_paper_as_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reference_id',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reference_type',
            field=models.CharField(choices=[('Custom', 'Custom'), ('Knowledge', 'Knowledge'), ('Paper', 'Paper'), ('Case', 'Case')], default='Custom', max_length=8, null=True),
        ),
    ]
